version: '3.7'

services:
  app:
    image: movie-booking-be:v1
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker_application.properties:/app/application.properties:ro
    env_file:
      - .env
    depends_on:
      - db
      # - redis

  db:
    profiles: [ "start" ]
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

#  redis:
#    image: redis:6-alpine
#    restart: always
#    volumes:
#      - ./.docker/data/redis:/var/lib/redis
