version: '3.7'

services: 
  app:
    image: movie-booking-be:v1
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker_application.properties:/app/application.properties:ro
    env_file:
      - .env
    # depends_on:
      # - db
      # - redis

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
    secrets:
      - db_root_password

secrets:
   db_dev_password:
     file: ./secrets/db_dev_password.txt
   db_password:
     file: ./secrets/db_password.txt
   db_root_password:
     file: ./secrets/db_root_password.txt

  # redis:
  #   image: redis:6-alpine
  #   restart: always
  #   volumes:
  #     - ./.docker/data/redis:/data
