version: '3.7'

services: 
  app:
    image: movie-booking-be:v1
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker_application.properties:/app/application.properties:ro
    env_file:
      - .env
      - .env.dev
    depends_on:
      - db
      # - redis

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOTPW}

  # redis:
  #   image: redis:6-alpine
  #   restart: always
  #   volumes:
  #     - ./.docker/data/redis:/data
