server:
  port: ${ENV_PORT:3000}

spring:
  application:
    name: ${ENV_NAME:movie_booking}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:database}
    username: ${DB_USER:root}
    password: ${DB_PASS:rootpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${DB_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${DB_HIBERNATE_DDL_AUTO:create-drop}
