server:
  port: ${ENV_PORT}



#spring.jpa.show-sql: true
springdoc:
  swagger-ui:
    oauth:
      client-id: public-client
      use-pkce-with-authorization-code-grant: true
    path=/swagger-ui-custom:
      html:
    url=/openapi-3:
      0:
        yml:
  oAuthFlow:
    authorizationUrl: ${BASE_URL}/oauth2/authorize
    tokenUrl: ${BASE_URL}/oauth2/token
  api-docs:
    path=/api-docs:


spring:

  security:

    oauth2:

      #      authorizationserver:
      #        client:
      #
      #          public-client:

      #            registration:
      #              client-id: "public-client"
      #              client-authentication-methods:
      #                - "none"
      #              authorization-grant-types:
      #                - "authorization_code"
      #              redirect-uris:
      #                - "https://oauth.pstmn.io/v1/browser-callback"
      #              #                - "http:localhost:8080/oauth2/callback/public-client"
      #
      #              scopes: openid,profile,email


      # hien ra cai bang kieu gg cho phep xem tem email, bla bla bla
      #            require-authorization-consent: true
      #            require-proof-key: true
      client:
        registration:
          google:
            clientId: 242257763708-v3424p6g9o1rr46q4vtuubvf5f4k5f7r.apps.googleusercontent.com
            clientSecret: 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
  #            redirect_uri: https://booking-movie-backend-3a547b1ac2e9.herokuapp.com/oauth2/callback/google
  config:
    import: optional:configtree:/run/secrets/ , optional:file:.env[.properties]
  application:
    name: ${ENV_NAME}
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${DB_SHOW_SQL}
    hibernate:
      ddl-auto: ${DB_HIBERNATE_DDL_AUTO}

logging:
  level:
    org.springframework.security: debug

jwt:
  key:
    id: 'configured-f57f-46a2-b502-8a24c308be7f'
    public: classpath:app.pub
    private: classpath:app.key
